name: Maven Build and Test

on:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: setup java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '17'

    - name: build using maven
      run: mvn clean install    

    - name: run test
      run: mvn test

    - name: Set up Docker Build
      uses: docker/setup-buildx-action@v2

    - name: build docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/java-app .

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: push image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/java-app
